# ######################################################################
# A TODO list for the
#	package schl v0.1
# 
# Tassos Tsesmetzis -- July 2019
# ######################################################################

* *A TODO list*
** TODO Make package TeX agnostic
   Currently, schl depends on /fontspec/ (for the command /\letterspace/). 
   This means that it runs on XeLaTeX and LuaTeX (?).
** TODO Merge macros /\lowerdots/ and /\blankspace/ into one.(???)
   Define a new macro (name /\blankspace/?) with two arguments. 
   First argument is optional -- the deviation from base line.
   Second argument is mandatory -- the length of the space.
   It must accept an option for the /style/ of the blank space
   (line, dotted, empty)
** DONE Define Greek math operators with better font control
   Is the font used in  /\sin, \cos, \tan, \cot, \gcd/ 
   and /\lcm/ good enough?
** TODO Better formating of the table in /\examdetailsii/
** DONE Delete macro /\signer/?
   Insert names in /\signatures/ without the need of /\signer/ macro,
   as part of argument #2.
** DONE Make a macro for True-False questions
** DONE Make a macro for matching questions.
** TODO Define internal macros for other languages.
** TODO Check the installation in systems not running Linux.
   Update the /README.md/.

* *Generate schl.sty and schl.pdf*
  
  #+begin_src bash
   rm schl.sty && xelatex schl.ins && xelatex schl.dtx && xelatex schl.dtx;
   cp schl.sty ~/texmf/tex/xelatex/schl/;
   cp languages/schl-greek.def ~/texmf/tex/xelatex/schl/languages/;
   cp languages/schl-template.def ~/texmf/tex/xelatex/schl/languages/;
  #+end_src
  
* *Make changes in all files*
  
  #+begin_src bash
   # working directory
   workdir=~/myProjects/schl
   # change
   oldVal=worksheethd;
   # with
   newVal=worksheethd;
   # Search and change common parameters in all files
   # except those in node_modules, bin and .git
   # if file {} is a regular file the substitute parVal with parName
   find ${workdir}/* -type d \( -path $(workdir)/node_modules -o -path $(pwd)/.git \) \
        -prune  -o \
        -exec test -f {} \; -exec sed -i -e "s/oldVal/newVal/g" {} \;
  #+end_src
